### ISSUE TITLE
ellipse-desc 

### ISSUE THREAD

**Issue by Nirco96** [articodeltd/angular-cesium#179]
hey,

I am using ac-ellipse-desc (version 0.0.33) 
whenever the layer is updated, the ellipse is flashing
i have noticed that it happends only when the material i define has transparency 

for example- when the material is red (248,77,80), it looks ok but when itis red with 60% transparency (248,77,80,153) it happends

thanks!
Roni Cohen :)

**Comment by nadavpld** [comment]
I'm not part of the developers team but I have encountered the same problem while using the regular cesiumJS with angular 1.X a while ago.
Using a callback property for the position and updating the position using it solved the problem but generated a new odd behavior.
https://groups.google.com/forum/#!topic/cesium-dev/Be4x-fVJepY

Eventually ended up removing this feature (cone) and using a SampledPositionProperty in order to create a smooth flight for other objects.

Never tought it was a transparency issue but as you can see there, the cone was half transparent too..
