### ISSUE TITLE
Feature Idea - When shapes are disabled allow mouse drag to rotate the globe.

### ISSUE THREAD

**Issue by anotherhale** [articodeltd/angular-cesium#325]
When you use the editor drawing tools and disable the shape and then try to left click while over the shape it does not rotate the globe. You must zoom out and be able to left click on the screen off of the disabled shape to rotate the globe. When you are zoomed in over the shape and want to pan along the map it becomes annoying to have to zoom out to accomplish this.

I think it would also be good to update the mouse icon when dragging shapes to the drag (hand) icon. (I can open a separate issue for that if you like).

To support backwards compatibility maybe we can pass in an option to the shape to allow this behavior?

**Version**
- angular-cesium@0.0.63

https://youtu.be/WJQwqK86vO4

**Comment by eitanfr** [comment]
Hi,
About the issue with rotating when a shape is disabled, this is a bug. fixed in #330 .

About adding icons, it can be implemented outside of angular-cesium., but it sounds like a nice idea to integrate it with angular-cesium. 
It's not relevant to this issue, so I am opening it as a new Feature idea, and of course, PRs are welcomed :)
